#!/bin/bash

# Get the first argument as the subcommand
SUBCOMMAND=$1
shift # Remove the subcommand from the arguments list

# Get the absolute path of the current script's directory
SCRIPT_ABS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

case "$SUBCOMMAND" in
    vscode)
        bash "$SCRIPT_ABS_DIR/bin/vscode.sh" "$@"
        ;;
    tunnel)
        bash "$SCRIPT_ABS_DIR/bin/tunnel.sh" "$@"
        ;;
    proxy)
        bash "$SCRIPT_ABS_DIR/bin/start_proxy.sh" "$@"
        ;;
    login)
        bash "$SCRIPT_ABS_DIR/bin/login_cloudflare.sh" "$@"
        ;;
    job)
        bash "$SCRIPT_ABS_DIR/bin/job.sh" "$@"
        ;;
    share)
        bash "$SCRIPT_ABS_DIR/bin/share.sh" "$@"
        ;;
    wget)
        bash "$SCRIPT_ABS_DIR/bin/wget.sh" "$@"
        ;;
    *)
        echo "Usage: rat-cli [vscode|tunnel|proxy|login|job|share|wget] [-- args <>]"
        echo "Compact Usage Summary:"
        echo "  rat-cli login: Logs into your Cloudflare account and copies the necessary certificate."
        echo "  rat-cli vscode [--port <PORT>] [--jumpserver <user@host>] [--domain <domain>]: Starts a VSCode instance, optionally with a specific port, jumpserver, or domain."
        echo "  rat-cli tunnel --port <PORT> [--domain <DOMAIN>] [--subpage_path <PATH>] [--protocol <http/ssh>]: Tunnels a local port to a public Cloudflare URL."
        echo "  rat-cli proxy --jumpserver <user@host>: Shares internet via a remote proxy server using a jumpserver."
        echo "  rat-cli job <node_ids> <gpu_nos> <cpu_nos> <domain_username> <node_name>: Submits a SLURM job with specified resources and domain."
        exit 1
        ;;
esac
