#!/bin/bash
DOMAIN="lonelycoder.live"

port=""
subdomain=""
subpage_path=""
# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --port)
            shift
            port="$1"
            ;;
        --domain)
            shift
            domain="$1"
            ;;
        --subpage_path)
            shift
            subpage_path="$1"
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done


CURPATH="$(dirname "$0")"
cd $CURPATH
echo $(pwd)

cleanup() {
    echo "Cleaning up..."
    pkill -P $$
    # rm -rf tunnels/${TUNNEL_NAME}
    # ./cloudflared-linux-amd64 tunnel delete ${TUNNEL_NAME}
    wait
    echo "Cleanup complete."
}

# Trap the EXIT signal and call the cleanup function
trap cleanup EXIT

if [ ! -n "$port" ]; then
    echo "Usage: $0 --port <PORT> [--domain <DOMAIN>] [--subpage_path <PATH>]"
    exit 1
fi

if [ -n "$domain" ]; then

  TUNNEL_NAME=${domain}_${port}
  mkdir -p tunnels/${TUNNEL_NAME}

  ./cloudflared-linux-amd64 tunnel --credentials-file tunnels/${TUNNEL_NAME}/creds.json create ${TUNNEL_NAME}

  json_data=$(cat tunnels/${TUNNEL_NAME}/creds.json)
  tunnel_id=$(echo "$json_data" | grep -o '"TunnelID":"[^"]*' | cut -d'"' -f4)

  yaml_content="""tunnel: ${tunnel_id}
credentials-file: tunnels/${TUNNEL_NAME}/creds.json

ingress:
  - hostname: ${domain}
    service: http://localhost:${port}
  - service: http_status:404
  """
  echo "$yaml_content" > tunnels/${TUNNEL_NAME}/config.yml
  ./cloudflared-linux-amd64 tunnel route dns ${tunnel_id} ${domain}

  date_time=$(date +"%Y-%m-%d %H:%M:%S")
  echo "$date_time: $1 --> https://${domain}" >> host.log

  highlight_url() {
      echo -e "\e[34m$1\e[0m"
  }
  echo '###############################'
  echo $(highlight_url "https://${domain}/${subpage_path}")
  echo '###############################'

  ./cloudflared-linux-amd64 tunnel --config  tunnels/${TUNNEL_NAME}/config.yml run ${tunnel_id}

else 

  log_file=cloudflare_log
  rm -f "$log_file"

  ./cloudflared-linux-amd64 tunnel --url http://localhost:${port} --logfile cloudflare_log  >> /dev/null 2>&1 &

  sleep 1
  while :; do
      result=$(grep -o 'https://[a-zA-Z0-9.-]*\.trycloudflare\.com' "$log_file")
      
      if [ -n "$result" ]; then
          echo "$result"/$subpage_path
          break
      fi
      sleep 1
  done

  date_time=$(date +"%Y-%m-%d %H:%M:%S")
  echo "$date_time: ${port} --> $result" >> host.log

  wait

fi
