#!/bin/bash
# Default values
jumpserver=""
port=""
domain=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --jumpserver)
            shift
            jumpserver="$1"
            ;;
        --port)
            shift
            port="$1"
            ;;
        --domain)
            shift
            domain="$1"
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done

CURPATH="$(dirname "$0")"
cd $CURPATH

if [ -n "$port" ]; then
    PORT=$port
else
    PORT=$(($RANDOM%1000+7000))
fi

VSCODE_IPC_HOOK_CLI= code-server*/bin/code-server --config config.yaml --user-data-dir vscode-user-dir  --extensions-dir vscode-extensions_dir  --bind-addr 127.0.0.1:$PORT >> /dev/null 2>&1 &
if [ -n "$jumpserver" ]; then
    echo reverse-tunneling port $PORT...
    ssh -R  "${PORT}":localhost:"${PORT}" -N  -o ExitOnForwardFailure=yes $jumpserver
elif [ -n "$domain" ]; then
    export TUNNEL_ORIGIN_CERT=cert.pem | bash tunnel --domain ${domain} --port ${PORT}
else
    bash tunnel --port ${PORT}
fi
